webtalk_init -webtalk_dir /home/marco/Documents/tesis/ww39_neuronal_new_IP/IP/hardware_for_IP/hardware_for_IP.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-06 22:32:46" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211503959_0_0_721" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hccsku1e03o3uu0ju4sp41q5r4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_47" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "47" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1578370652000" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key hwid -value "1578186480000" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key bspid -value "1578186732000" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key os -value "freertos823_xilinx" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key apptemplate -value "freertos_hello_world" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key projSize -value "614.34375" -context "sdk\\\\application/1578370652000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1578371566370"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1578371566370"
webtalk_transmit -clientid 3308207841 -regid "211503959_0_0_721" -xml /home/marco/Documents/tesis/ww39_neuronal_new_IP/IP/hardware_for_IP/hardware_for_IP.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/marco/Documents/tesis/ww39_neuronal_new_IP/IP/hardware_for_IP/hardware_for_IP.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/marco/Documents/tesis/ww39_neuronal_new_IP/IP/hardware_for_IP/hardware_for_IP.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
