// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _I_calc_HH_
#define _I_calc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "getTotalCurrent.h"
#include "GapJunctionIP_fadvdy.h"
#include "I_calc_F_temp_data.h"

namespace ap_rtl {

struct I_calc : public sc_module {
    // Port declarations 41
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > output_r_TDATA;
    sc_out< sc_logic > output_r_TVALID;
    sc_in< sc_logic > output_r_TREADY;
    sc_out< sc_lv<1> > output_r_TLAST;
    sc_in< sc_lv<27> > simConfig_rowsToSimu_dout;
    sc_in< sc_logic > simConfig_rowsToSimu_empty_n;
    sc_out< sc_logic > simConfig_rowsToSimu_read;
    sc_in< sc_lv<27> > simConfig_BLOCK_NUMBERS_V_dout;
    sc_in< sc_logic > simConfig_BLOCK_NUMBERS_V_empty_n;
    sc_out< sc_logic > simConfig_BLOCK_NUMBERS_V_read;
    sc_in< sc_lv<32> > F_acc_V_data_0_dout;
    sc_in< sc_logic > F_acc_V_data_0_empty_n;
    sc_out< sc_logic > F_acc_V_data_0_read;
    sc_in< sc_lv<32> > F_acc_V_data_1_dout;
    sc_in< sc_logic > F_acc_V_data_1_empty_n;
    sc_out< sc_logic > F_acc_V_data_1_read;
    sc_in< sc_lv<32> > F_acc_V_data_2_dout;
    sc_in< sc_logic > F_acc_V_data_2_empty_n;
    sc_out< sc_logic > F_acc_V_data_2_read;
    sc_in< sc_lv<32> > F_acc_V_data_3_dout;
    sc_in< sc_logic > F_acc_V_data_3_empty_n;
    sc_out< sc_logic > F_acc_V_data_3_read;
    sc_in< sc_lv<32> > V_acc_V_data_0_dout;
    sc_in< sc_logic > V_acc_V_data_0_empty_n;
    sc_out< sc_logic > V_acc_V_data_0_read;
    sc_in< sc_lv<32> > V_acc_V_data_1_dout;
    sc_in< sc_logic > V_acc_V_data_1_empty_n;
    sc_out< sc_logic > V_acc_V_data_1_read;
    sc_in< sc_lv<32> > V_acc_V_data_2_dout;
    sc_in< sc_logic > V_acc_V_data_2_empty_n;
    sc_out< sc_logic > V_acc_V_data_2_read;
    sc_in< sc_lv<32> > V_acc_V_data_3_dout;
    sc_in< sc_logic > V_acc_V_data_3_empty_n;
    sc_out< sc_logic > V_acc_V_data_3_read;


    // Module declarations
    I_calc(sc_module_name name);
    SC_HAS_PROCESS(I_calc);

    ~I_calc();

    sc_trace_file* mVcdFile;

    I_calc_F_temp_data* F_temp_data_U;
    I_calc_F_temp_data* V_temp_data_U;
    getTotalCurrent* grp_getTotalCurrent_fu_357;
    GapJunctionIP_fadvdy<1,8,32,32,32>* GapJunctionIP_fadvdy_x_U201;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<14> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_logic > simConfig_rowsToSimu_blk_n;
    sc_signal< sc_logic > simConfig_BLOCK_NUMBERS_V_blk_n;
    sc_signal< sc_logic > F_acc_V_data_0_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_35_i_i_reg_525;
    sc_signal< sc_logic > F_acc_V_data_1_blk_n;
    sc_signal< sc_logic > F_acc_V_data_2_blk_n;
    sc_signal< sc_logic > F_acc_V_data_3_blk_n;
    sc_signal< sc_logic > V_acc_V_data_0_blk_n;
    sc_signal< sc_logic > V_acc_V_data_1_blk_n;
    sc_signal< sc_logic > V_acc_V_data_2_blk_n;
    sc_signal< sc_logic > V_acc_V_data_3_blk_n;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_3_reg_238;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_3_reg_250;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_2_reg_262;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_2_reg_274;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_1_reg_286;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_1_reg_298;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_reg_310;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_reg_322;
    sc_signal< sc_lv<26> > block_i_i_reg_334;
    sc_signal< sc_lv<27> > simConfig_BLOCK_NUMB_reg_458;
    sc_signal< bool > ap_condition_135;
    sc_signal< sc_lv<27> > simConfig_rowsToSimu_8_reg_463;
    sc_signal< sc_lv<26> > RowOfBlocks_V_1_fu_393_p2;
    sc_signal< sc_lv<26> > RowOfBlocks_V_1_reg_520;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_35_i_i_fu_403_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter1_tmp_35_i_i_reg_525;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter2_tmp_35_i_i_reg_525;
    sc_signal< sc_lv<26> > block_fu_408_p2;
    sc_signal< sc_lv<26> > block_reg_529;
    sc_signal< sc_lv<32> > tmp_data_0_reg_534;
    sc_signal< sc_logic > F_acc_V_data_00_status;
    sc_signal< sc_logic > V_acc_V_data_00_status;
    sc_signal< bool > ap_condition_188;
    sc_signal< sc_lv<32> > tmp_data_1_reg_539;
    sc_signal< sc_lv<32> > tmp_data_2_reg_544;
    sc_signal< sc_lv<32> > tmp_data_3_reg_549;
    sc_signal< sc_lv<32> > tmp_data_0_9_reg_554;
    sc_signal< sc_lv<32> > tmp_data_1_9_reg_559;
    sc_signal< sc_lv<32> > tmp_data_2_9_reg_564;
    sc_signal< sc_lv<32> > tmp_data_3_9_reg_569;
    sc_signal< sc_lv<32> > grp_fu_372_p2;
    sc_signal< sc_lv<32> > tmp_53_i_i_reg_574;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<32> > tmp_54_i_i_reg_580;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage2;
    sc_signal< sc_lv<32> > tmp_53_1_i_i_reg_586;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage3;
    sc_signal< sc_lv<32> > tmp_54_1_i_i_reg_592;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage4;
    sc_signal< sc_lv<32> > tmp_53_2_i_i_reg_598;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage5;
    sc_signal< sc_lv<32> > tmp_54_2_i_i_reg_604;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage6;
    sc_signal< sc_lv<32> > tmp_53_3_i_i_reg_610;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage7;
    sc_signal< sc_lv<32> > tmp_54_3_i_i_reg_616;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<3> > row_fu_452_p2;
    sc_signal< sc_lv<3> > row_reg_625;
    sc_signal< sc_lv<1> > ap_CS_fsm_state23;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<2> > F_temp_data_address0;
    sc_signal< sc_logic > F_temp_data_ce0;
    sc_signal< sc_logic > F_temp_data_we0;
    sc_signal< sc_lv<32> > F_temp_data_d0;
    sc_signal< sc_lv<32> > F_temp_data_q0;
    sc_signal< sc_lv<2> > F_temp_data_address1;
    sc_signal< sc_logic > F_temp_data_ce1;
    sc_signal< sc_logic > F_temp_data_we1;
    sc_signal< sc_lv<32> > F_temp_data_d1;
    sc_signal< sc_lv<2> > V_temp_data_address0;
    sc_signal< sc_logic > V_temp_data_ce0;
    sc_signal< sc_logic > V_temp_data_we0;
    sc_signal< sc_lv<32> > V_temp_data_d0;
    sc_signal< sc_lv<32> > V_temp_data_q0;
    sc_signal< sc_lv<2> > V_temp_data_address1;
    sc_signal< sc_logic > V_temp_data_ce1;
    sc_signal< sc_logic > V_temp_data_we1;
    sc_signal< sc_lv<32> > V_temp_data_d1;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_ap_start;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_ap_done;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_ap_idle;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_ap_ready;
    sc_signal< sc_lv<32> > grp_getTotalCurrent_fu_357_output_r_TDATA;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_output_r_TVALID;
    sc_signal< sc_lv<1> > grp_getTotalCurrent_fu_357_output_r_TLAST;
    sc_signal< sc_lv<2> > grp_getTotalCurrent_fu_357_F_temp_data_address0;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_F_temp_data_ce0;
    sc_signal< sc_lv<2> > grp_getTotalCurrent_fu_357_V_temp_data_address0;
    sc_signal< sc_logic > grp_getTotalCurrent_fu_357_V_temp_data_ce0;
    sc_signal< sc_lv<26> > RowOfBlocks_V_reg_226;
    sc_signal< sc_lv<1> > exitcond_i_i_fu_446_p2;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_3_phi_fu_242_p4;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_3_phi_fu_254_p4;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_2_phi_fu_266_p4;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_2_phi_fu_278_p4;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_1_phi_fu_290_p4;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_1_phi_fu_302_p4;
    sc_signal< sc_lv<32> > V_temp_data_i_i_load_phi_fu_314_p4;
    sc_signal< sc_lv<32> > F_temp_data_i_i_load_phi_fu_326_p4;
    sc_signal< sc_lv<26> > block_i_i_phi_fu_338_p4;
    sc_signal< sc_lv<3> > val_assign_reg_345;
    sc_signal< sc_lv<1> > ap_CS_fsm_state24;
    sc_signal< sc_lv<1> > ap_CS_fsm_state22;
    sc_signal< sc_logic > ap_reg_grp_getTotalCurrent_fu_357_ap_start;
    sc_signal< sc_logic > F_acc_V_data_00_update;
    sc_signal< sc_logic > V_acc_V_data_00_update;
    sc_signal< sc_lv<1> > tmp_i_i_fu_388_p2;
    sc_signal< sc_lv<32> > grp_fu_372_p0;
    sc_signal< sc_lv<32> > grp_fu_372_p1;
    sc_signal< sc_lv<27> > RowOfBlocks_V_cast_i_fu_384_p1;
    sc_signal< sc_lv<27> > block_i_i_cast_fu_399_p1;
    sc_signal< sc_logic > grp_fu_372_ce;
    sc_signal< sc_lv<14> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<14> ap_ST_fsm_state1;
    static const sc_lv<14> ap_ST_fsm_state2;
    static const sc_lv<14> ap_ST_fsm_state3;
    static const sc_lv<14> ap_ST_fsm_pp0_stage0;
    static const sc_lv<14> ap_ST_fsm_pp0_stage1;
    static const sc_lv<14> ap_ST_fsm_pp0_stage2;
    static const sc_lv<14> ap_ST_fsm_pp0_stage3;
    static const sc_lv<14> ap_ST_fsm_pp0_stage4;
    static const sc_lv<14> ap_ST_fsm_pp0_stage5;
    static const sc_lv<14> ap_ST_fsm_pp0_stage6;
    static const sc_lv<14> ap_ST_fsm_pp0_stage7;
    static const sc_lv<14> ap_ST_fsm_state22;
    static const sc_lv<14> ap_ST_fsm_state23;
    static const sc_lv<14> ap_ST_fsm_state24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<26> ap_const_lv26_0;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<26> ap_const_lv26_1;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_F_acc_V_data_00_status();
    void thread_F_acc_V_data_00_update();
    void thread_F_acc_V_data_0_blk_n();
    void thread_F_acc_V_data_0_read();
    void thread_F_acc_V_data_1_blk_n();
    void thread_F_acc_V_data_1_read();
    void thread_F_acc_V_data_2_blk_n();
    void thread_F_acc_V_data_2_read();
    void thread_F_acc_V_data_3_blk_n();
    void thread_F_acc_V_data_3_read();
    void thread_F_temp_data_address0();
    void thread_F_temp_data_address1();
    void thread_F_temp_data_ce0();
    void thread_F_temp_data_ce1();
    void thread_F_temp_data_d0();
    void thread_F_temp_data_d1();
    void thread_F_temp_data_i_i_load_1_phi_fu_302_p4();
    void thread_F_temp_data_i_i_load_2_phi_fu_278_p4();
    void thread_F_temp_data_i_i_load_3_phi_fu_254_p4();
    void thread_F_temp_data_i_i_load_phi_fu_326_p4();
    void thread_F_temp_data_we0();
    void thread_F_temp_data_we1();
    void thread_RowOfBlocks_V_1_fu_393_p2();
    void thread_RowOfBlocks_V_cast_i_fu_384_p1();
    void thread_V_acc_V_data_00_status();
    void thread_V_acc_V_data_00_update();
    void thread_V_acc_V_data_0_blk_n();
    void thread_V_acc_V_data_0_read();
    void thread_V_acc_V_data_1_blk_n();
    void thread_V_acc_V_data_1_read();
    void thread_V_acc_V_data_2_blk_n();
    void thread_V_acc_V_data_2_read();
    void thread_V_acc_V_data_3_blk_n();
    void thread_V_acc_V_data_3_read();
    void thread_V_temp_data_address0();
    void thread_V_temp_data_address1();
    void thread_V_temp_data_ce0();
    void thread_V_temp_data_ce1();
    void thread_V_temp_data_d0();
    void thread_V_temp_data_d1();
    void thread_V_temp_data_i_i_load_1_phi_fu_290_p4();
    void thread_V_temp_data_i_i_load_2_phi_fu_266_p4();
    void thread_V_temp_data_i_i_load_3_phi_fu_242_p4();
    void thread_V_temp_data_i_i_load_phi_fu_314_p4();
    void thread_V_temp_data_we0();
    void thread_V_temp_data_we1();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage3();
    void thread_ap_CS_fsm_pp0_stage4();
    void thread_ap_CS_fsm_pp0_stage5();
    void thread_ap_CS_fsm_pp0_stage6();
    void thread_ap_CS_fsm_pp0_stage7();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_condition_135();
    void thread_ap_condition_188();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_block_fu_408_p2();
    void thread_block_i_i_cast_fu_399_p1();
    void thread_block_i_i_phi_fu_338_p4();
    void thread_exitcond_i_i_fu_446_p2();
    void thread_grp_fu_372_ce();
    void thread_grp_fu_372_p0();
    void thread_grp_fu_372_p1();
    void thread_grp_getTotalCurrent_fu_357_ap_start();
    void thread_output_r_TDATA();
    void thread_output_r_TLAST();
    void thread_output_r_TVALID();
    void thread_row_fu_452_p2();
    void thread_simConfig_BLOCK_NUMBERS_V_blk_n();
    void thread_simConfig_BLOCK_NUMBERS_V_read();
    void thread_simConfig_rowsToSimu_blk_n();
    void thread_simConfig_rowsToSimu_read();
    void thread_tmp_35_i_i_fu_403_p2();
    void thread_tmp_i_i_fu_388_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
