# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths /home/marco/Documents/tesis/ww39_neuronal_new_IP/IP_2020_latest_Jan/IP_latest_2020_Enero/solution1/impl/ip [current_project]
update_ip_catalog
set_property ip_output_repo /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_AXILiteS_s_axi.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_dadd_64ns_64ns_64_8_full_dsp_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_dmul_64ns_64ns_64_9_max_dsp_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_fexp_32ns_32ns_32_13_full_dsp_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_fmul_32ns_32ns_32_4_max_dsp_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_fpext_32ns_64_1_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_fptrunc_64ns_32_2_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_fsub_32ns_32ns_32_8_full_dsp_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_mul_27ns_27ns_54_7_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP_mul_27ns_29ns_56_3_1.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/I_calc.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/I_calc_F_temp_data.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/V_read.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/V_read_entry190203.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/V_read_voltagesBackup.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/V_read_voltagesBackup_memcore.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/acc.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/blockControl.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/calc.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/execute.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/execute_Block_codeRe.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/execute_entry195.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w1_d128_A.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w27_d1024_A.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w27_d2_A.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w27_d2_A_x.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w27_d3_A.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w27_d3_A_x.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w32_d128_A.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w32_d2_A.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/fifo_w32_d2_A_x.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/getConductances.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/getTotalCurrent.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/getVoltages.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/indexGeneration.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/readCalcData.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/readVoltages.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/start_for_I_calc_U0.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/start_for_acc_U0.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/start_for_calc_U0.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/start_for_execute_Block_codeRe_U0.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/start_for_indexGeneration_U0.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/writeV2calc.v
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/verilog/GapJunctionIP.v
}
read_vhdl -library xil_defaultlib {
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_dadd_6_full_dsp_64.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_dmul_7_max_dsp_64.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_fadd_6_full_dsp_32.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_fexp_11_full_dsp_32.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_fmul_2_max_dsp_32.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_fpext_0_no_dsp_32.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_fptrunc_0_no_dsp_64.vhd
  /home/marco/Documents/tesis/ww39_neuronal_new_IP/2020_newIP_project1/project_1/project_1.srcs/sources_1/imports/ip/hdl/ip/GapJunctionIP_ap_fsub_6_full_dsp_32.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top GapJunctionIP -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef GapJunctionIP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file GapJunctionIP_utilization_synth.rpt -pb GapJunctionIP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
